"""initial schema: all tenant tables + pgvector

The first revision builds the schema from the current models (single-shot bootstrap).
Every later change should be an autogenerated, explicit revision:
    alembic revision --autogenerate -m "describe change"
"""
from alembic import op

from app.core.db import Base
import app.models  # noqa: F401

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(bind=op.get_bind())
    # Approximate nearest-neighbour index; the salon_id btree index + WHERE keeps results tenant-scoped.
    op.execute("CREATE INDEX IF NOT EXISTS ix_chunks_embedding_hnsw ON document_chunks "
               "USING hnsw (embedding vector_cosine_ops)")


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
